# -*- coding: utf-8 -*-

categorias = {
    1: u'AUTO',
    9: u'Carros',
    14: u'Motocicletas, motocicletas',
    81: u'Camiões e autocarros',
    11: u'Veículos de água',
    10: u'Peças e Acessórios',

    4: u'BENS IMÓVEIS',
    86: u'Apartamentos',
    23: u'Quartos',
    25: u'Moradias, quintas, casas de campo',
    26: u'Terrenos',
    85: u'Garagens e estacionamentos',
    42: u'Aluguer lojas/comercial',
    24: u'Bens no estrangeiro',

    110: u'TRABALHO',
    111: u'Empregos',
    112: u'Currículos',

    113: u'SERVIÇOS',
    115: u'Oferta de serviços',
    114: u'Solicitação de serviços',

    5: u'PARAFERNÁLIA',
    27: u'Roupas, sapatos, acessórios',
    29: u'Vestuário e calçado para crianças',
    30: u'Produtos para crianças e brinquedos',
    28: u'Relógios e Jóias',
    88: u'Beleza & Saúde',

    2: u'CASA E JARDIM',
    21: u'Electrodomésticos',
    20: u'Mobiliário e interior',
    87: u'Pratos e utensílios de cozinha',
    82: u'Comida',
    19: u'Reparação e construção',
    106: u'Plantas',

    6: u'ELETRÔNICOS DE CONSUMO',
    32: u'Áudio e vídeo (p.ex televisões, aparelhagens)',
    97: u'Jogos, consolas e software',
    31: u'Desktops',
    98: u'Portáteis',
    99: u'Equipamentos de escritório e consumíveis',
    96: u'Tablets e e-books',
    84: u'Telemóveis',
    105: u'Câmaras fotográficas',
    101: u'Peças e acessórios',

    7: u'HOBBIES E LAZER',
    33: u'Viagens & Turismo',
    34: u'Bicicletas',
    83: u'Livros e Revistas',
    36: u'Colecionadores',
    38: u'Instrumentos musicais',
    102: u'Caça e pesca',
    39: u'Desportos',

    35: u'ANIMAIS',
    89: u'Cães',
    90: u'Gatos',
    91: u'Aves',
    92: u'Peixes e aquários',
    93: u'Outros animais',
    94: u'Artigos para animais',

    8: u'PARA NEGÓCIOS',
    116: u'Negócios/lojas para venda',
    40: u'Equipamento negócios',
}
