categorias = {
    1: 'AUTO',
    9: 'Carros',
    14: 'Motocicletas, motocicletas',
    81: 'Camioes e autocarros',
    11: 'Veiculos de agua',
    10: 'Pecas e Acessorios',

    4: 'BENS IMOVEIS',
    86: 'Apartamentos',
    23: 'Quartos',
    25: 'Moradias, quintas, casas de campo',
    26: 'Terrenos',
    85: 'Garagens e estacionamentos',
    42: 'Aluguer lojas/comercial',
    24: 'Bens no estrangeiro',

    110: 'TRABALHO',
    111: 'Empregos',
    112: 'Curriculos',

    113: 'SERVICOS',
    115: 'Oferta de servicos',
    114: 'Solicitacao de servicos',

    5: 'PARAFERNALIA',
    27: 'Roupas, sapatos, acessorios',
    29: 'Vestuario e calcado para criancas',
    30: 'Produtos para criancas e brinquedos',
    28: 'Relogios e Joias',
    88: 'Beleza & Saude',

    2: 'CASA E JARDIM',
    21: 'Electrodomesticos',
    20: 'Mobiliario e interior',
    87: 'Pratos e utensilios de cozinha',
    82: 'Comida',
    19: 'Reparacao e construcao',
    106: 'Plantas',

    6: 'ELETRONICOS DE CONSUMO',
    32: 'Audio e video (p.ex televisoes, aparelhagens)',
    97: 'Jogos, consolas e software',
    31: 'Desktops',
    98: 'Portateis',
    99: 'Equipamentos de escritorio e consumiveis',
    96: 'Tablets e e-books',
    84: 'Telemoveis',
    105: 'Camaras fotograficas',
    101: 'Pecas e acessorios',

    7: 'HOBBIES E LAZER',
    33: 'Viagens e Turismo',
    34: 'Bicicletas',
    83: 'Livros e Revistas',
    36: 'Colecionadores',
    38: 'Instrumentos musicais',
    102: 'Caca e pesca',
    39: 'Desportos',

    35: 'ANIMAIS',
    89: 'Caes',
    90: 'Gatos',
    91: 'Aves',
    92: 'Peixes e aquarios',
    93: 'Outros animais',
    94: 'Artigos para animais',

    8: 'PARA NEGOCIOS',
    116: 'Negocios/lojas para venda',
    40: 'Equipamento negocios',
}
